import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: 'שווה מכרזים | נתונים חיים ממינהל הרכש הממשלתי',
    description: 'מנוע מכרזים חכם — עדכון יומי מנח"ר ומינהל הרכש הממשלתי',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
          <html lang="he" dir="rtl">
                <body>
                  {children}
                        <style>{`
                                  @media (max-width: 768px) {
                                              /* Dashboard sidebar: hide on mobile */
                                                          [style*="flex: 0 0 238px"],
                                                                      [style*="flex:0 0 238px"] {
                                                                                    display: none !important;
                                                                                                }
                                                                                                            /* Dashboard main area: full width */
                                                                                                                        [style*="display: flex"][style*="min-height: 100vh"] > div:not([style*="flex: 0 0 238px"]):not([style*="flex:0 0 238px"]) {
                                                                                                                                      flex: 1 1 auto !important;
                                                                                                                                                    min-width: 0 !important;
                                                                                                                                                                }
                                                                                                                                                                            /* Stats row: 2 columns on mobile */
                                                                                                                                                                                        [style*="grid-template-columns: repeat(4"] {
                                                                                                                                                                                                      grid-template-columns: repeat(2, 1fr) !important;
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                              /* Topbar: wrap on mobile */
                                                                                                                                                                                                                                          [style*="height: 56px"] {
                                                                                                                                                                                                                                                        height: auto !important;
                                                                                                                                                                                                                                                                      min-height: 56px !important;
                                                                                                                                                                                                                                                                                    flex-wrap: wrap !important;
                                                                                                                                                                                                                                                                                                  padding: 8px 16px !important;
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                          /* Hide topbar search on mobile */
                                                                                                                                                                                                                                                                                                                                      [style*="border-radius: 10px"][style*="background: rgb(255, 255, 255)"][style*="flex: 1"] {
                                                                                                                                                                                                                                                                                                                                                    display: none !important;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            /* Inner page content */
                                                                                                                                                                                                                                                                                                                                                                                        .inner-page-content {
                                                                                                                                                                                                                                                                                                                                                                                                      padding: 14px 14px 32px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                              .inner-card {
                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 18px 14px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .detail-grid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  grid-template-columns: 1fr !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .tender-title {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-size: 1.15rem !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .docs-grid {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              grid-template-columns: 1fr !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .tender-actions {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex-direction: column !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .btn-primary, .btn-secondary {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text-align: center !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /* Nav hamburger */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .nav-hamburger {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: flex !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .nav-row {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: none !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                top: 65px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .nav-row.nav-row-open {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: flex !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex-direction: column !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  align-items: flex-start !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 8px 16px 12px !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              gap: 0 !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .nav-link {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 10px 0 !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: 100% !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border-bottom: 1px solid #eef4fa !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Topbar nav links on dashboard: hide on mobile */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .topbar-nav { display: none !important; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @media (max-width: 480px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* Extra small: stack tender card tags */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [style*="grid-template-columns: repeat(4"] {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              grid-template-columns: 1fr 1fr !important;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `}</style>style>
                </body>body>
          </html>html>
        )
}
</html>
