'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function RegisterPage() {
  const router = useRouter();
    const [step, setStep] = useState(1);
      const [loading, setLoading] = useState(false);
        const [form, setForm] = useState({
            businessName: '', ownerName: '', email: '', phone: '',
                category: '', region: '', employees: '', notification: 'whatsapp',
                  });
                    const upd = (f: string, v: string) => setForm((p) => ({ ...p, [f]: v }));
                      const handleSubmit = async () => {
                          setLoading(true);
                              try {
                                    const res = await fetch('/api/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
                                          if (res.ok) router.push('/dashboard');
                                              } catch (e) { console.error(e); }
                                                  finally { setLoading(false); }
                                                    };
                                                      const fields = [
                                                          { f: 'businessName', l: 'Business Name', t: 'text' },
                                                              { f: 'ownerName', l: 'Owner Name', t: 'text' },
                                                                  { f: 'email', l: 'Email', t: 'email' },
                                                                      { f: 'phone', l: 'Phone', t: 'tel' },
                                                                        ];
                                                                          const cats = ['Technology','Construction','Health','Education','Cleaning','Food','Security','Environment','Other'];
                                                                            const regs = ['Nationwide','North','Center','South','Jerusalem','Haifa'];
                                                                              return (
                                                                                  <main className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                                                                                        <div className="bg-white rounded-2xl shadow-lg p-8 w-full max-w-md">
                                                                                                <div className="flex justify-between mb-8">
                                                                                                          {[1,2,3].map((n) => (
                                                                                                                      <div key={n} className={'flex-1 h-2 rounded-full mx-1 ' + (step >= n ? 'bg-indigo-600' : 'bg-gray-200')} />
                                                                                                                                ))}
                                                                                                                                        </div>
                                                                                                                                                {step === 1 && (
                                                                                                                                                          <div className="space-y-4">
                                                                                                                                                                      <h2 className="text-2xl font-bold mb-6">Business Details</h2>
                                                                                                                                                                                  {fields.map(({ f, l, t }) => (
                                                                                                                                                                                                <div key={f}>
                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-1">{l}</label>
                                                                                                                                                                                                                                <input type={t} value={form[f as keyof typeof form]} onChange={(e) => upd(f, e.target.value)}
                                                                                                                                                                                                                                                  className="w-full border border-gray-300 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-indigo-400" />
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                        <button onClick={() => setStep(2)} disabled={!form.businessName || !form.email || !form.phone}
                                                                                                                                                                                                                                                                                                      className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-gray-300 text-white font-bold py-3 rounded-xl">Next</button>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                {step === 2 && (
                                                                                                                                                                                                                                                                                                                                          <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold mb-6">Business Profile</h2>
                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
                                                                                                                                                                                                                                                                                                                                                                                              <select value={form.category} onChange={(e) => upd('category', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full border border-gray-300 rounded-xl px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Select...</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                              {cats.map((c) => <option key={c} value={c}>{c}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium text-gray-700 mb-1">Region</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <select value={form.region} onChange={(e) => upd('region', e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full border border-gray-300 rounded-xl px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">Select...</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {regs.map((r) => <option key={r} value={r}>{r}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => setStep(1)} className="flex-1 border border-gray-300 text-gray-600 font-bold py-3 rounded-xl">Back</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setStep(3)} disabled={!form.category || !form.region}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex-1 bg-indigo-600 hover:bg-indigo-700 disabled:bg-gray-300 text-white font-bold py-3 rounded-xl">Next</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {step === 3 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold mb-6">Notifications</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {[{ v: 'whatsapp', l: 'WhatsApp', i: '📱' }, { v: 'email', l: 'Email', i: '📧' }, { v: 'both', l: 'Both', i: '🔔' }].map(({ v, l, i }) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label key={v} className={'flex items-center gap-4 p-4 border-2 rounded-xl cursor-pointer ' + (form.notification === v ? 'border-indigo-500 bg-indigo-50' : 'border-gray-200')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="radio" name="notification" value={v} checked={form.notification === v} onChange={() => upd('notification', v)} className="sr-only" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-2xl">{i}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="font-medium">{l}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-3 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => setStep(2)} className="flex-1 border border-gray-300 text-gray-600 font-bold py-3 rounded-xl">Back</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={handleSubmit} disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex-1 bg-green-600 hover:bg-green-700 disabled:bg-gray-300 text-white font-bold py-3 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Saving...' : 'Register'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }